sudo: required
services:
  - docker
language: ruby
branches:
  only:
    - master
script:
  - "rake $TASK"
env:
  - TASK=test:mtest
  - TASK=test:bintest
  - TASK=release:build
allow_failures:
  - env: TASK=release:build
