sudo: required
language: ruby
branches:
  only:
    - master
script:
  - "rake $TASK"
matrix:
  include:
    - env: TASK=test:mtest
      services: docker
    - env: TASK=test:integration
      services: docker
    - env: TASK=release:build
      services: docker
  allow_failures:
    - env: TASK=release:build
      services: docker
