compile: &defaults
  build: .
  volumes:
    - .:/home/mruby/code:rw
  command: rake compile BUILD_TARGET=all
test:
  <<: *defaults
  command: rake test
mtest:
  <<: *defaults
  command: rake test:mtest
clean:
  <<: *defaults
  command: rake clean
shell:
  <<: *defaults
  command: bash
